[[headers]] 
  for = "/*" 
  [headers.values] 
    Content-Security-Policy = '''
    default-src *;
    connect-src * data:;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    img-src 'self' data: https://firebasestorage.googleapis.com blob: https://graimer.netlify.app;'''
