[[headers]] 
  for = "/*" 
  [headers.values] 
    Content-Security-Policy = '''
    default-src 'self';
    connect-src 'self';
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    img-src 'self';'''
