[[headers]] 
  for = "/*" 
  [headers.values] 
    Content-Security-Policy = '''
    default-src *;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    img-src 'self' data: https://firebasestorage.googleapis.com;'''
